inodes threshold doc
topolvm/pvc-autoresizer pull request #105
Opened 2022-03-22 17:36 UTC by bells17

#98 #65

2022-03-30 09:04 UTC, peng225 requested changes

2022-03-30 09:04 UTC, peng225 commented on README.md
>  The PVC can optionally have `resize.topolvm.io/threshold` and `resize.topolvm.io/increase` annotations.
```suggestion
The PVC can optionally have `resize.topolvm.io/threshold`, `resize.topolvm.io/inodes-threshold` and `resize.topolvm.io/increase` annotations.
```

2022-03-31 00:00 UTC, peng225 submitted a review, later dismissed

2022-03-31 08:30 UTC, daichimukai requested changes
I suggest a minor language improvement.

2022-03-31 08:30 UTC, daichimukai commented on README.md
> +or the amount of free number of the inodes is below `resize.topolvm.io/inodes-threshold`,
```suggestion
or the number of free inodes is below `resize.topolvm.io/inodes-threshold`,
```

2022-03-31 09:20 UTC, daichimukai approved these changes

2022-03-31 23:56 UTC, peng225 approved these changes

2022-03-31 23:56 UTC, merged