add serviceMonitor
topolvm/pvc-autoresizer pull request #149
Opened 2022-10-10 06:42 UTC by mweibel

2022-10-18 00:55 UTC, llamerada-jp requested changes
Thank you for your PR.
Would you please add a note that encourages users to check this feature when enabling it because I have no plan to test it in CI?

2022-10-18 08:07 UTC, mweibel commented
sure, should I adjust the CHANGELOG.md of the chart for this?

2022-10-18 08:53 UTC, llamerada-jp commented
@mweibel 
Hi,

It is written in the description of value looks better. This is because new users may not look at the changelogs.
And would you update `chart/pvc-autoresizer/README.md` like the below link?
https://github.com/topolvm/pvc-autoresizer/blob/main/charts/pvc-autoresizer/README.md#update-readme

2022-10-19 05:45 UTC, mweibel commented
@llamerada-jp updated the PR with the changes. Please review again.

2022-10-20 00:31 UTC, llamerada-jp commented on charts/pvc-autoresizer/values.yaml
> +# deploy a ServiceMonitor. This is not tested in CI so make sure to test it yourself.
This comment is not output in README.md. Would you please adjust it?

2022-10-20 00:31 UTC, llamerada-jp commented on charts/pvc-autoresizer/values.yaml
> +  ## [Kube Prometheus Selector Label](https://github.com/helm/charts/tree/master/stable/prometheus-operator#exporters)
Ditto

2022-10-20 05:45 UTC, mweibel commented
@llamerada-jp adjusted..

2022-10-24 08:30 UTC, llamerada-jp reviewed
Is this setting for pod scraping? I read [the official document](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.ServiceMonitor) but I couldn't check it. The current helm chart of pvc-autoresizer doesn't generate service or endpoint resources. Do you know a good document about it?

2022-10-24 08:50 UTC, mweibel commented
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#deploying-a-sample-application

does that help to explain it?

2022-10-24 10:27 UTC, llamerada-jp commented
@mweibel 
Thank you for your reply. That document is helpful. According to that document, The [`PodMonitors`](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#using-podmonitors) resource looks suitable in this situation because the service resource does not exist for the pvc-autoresizer's pod. Would you please check it?

2022-11-07 06:06 UTC, mweibel commented
uh, that's a little embarassing :flushed: 

you're of course right - fixed!

2022-11-07 08:17 UTC, mweibel commented
I can't currently verify this though, the PodMonitor does not get picked up for some reason. Checking and will report back when this works.

2022-11-08 07:43 UTC, mweibel commented
regenerated the docs, too.

2022-11-08 10:24 UTC, llamerada-jp approved these changes
LGTM

2022-11-09 07:52 UTC, daichimukai approved these changes

2022-11-09 07:52 UTC, merged