Use mermaid to draw diagram
topolvm/pvc-autoresizer pull request #164
Opened 2023-01-01 10:23 UTC by toshipp

To ease to edit and delete dependency to external service.

2023-01-10 07:42 UTC, peng225 submitted a review, later dismissed

2023-01-12 01:43 UTC, pluser requested changes
The new mermaid diagram is hard to read when in dark mode.

![2023-01-12 10 30 41 github com e560efab4202](https://user-images.githubusercontent.com/1411155/211955765-6ea19828-78b3-49b5-a3e8-a63580cac63c.png)
Would you consider using a white background instead of a transparent one?

cf. [Background color changed in mermaid-js #1553](https://github.com/mermaid-js/mermaid/issues/1553#issuecomment-954798254)

2023-01-12 08:39 UTC, toshipp commented
@pluser Unfortunately, current implementation can not accept to change background color. I now add a subgraph to include whole objects and set fill for the subgraph.

2023-01-12 08:42 UTC, pluser approved these changes
😭

2023-01-13 00:04 UTC, peng225 approved these changes

2023-01-13 00:04 UTC, merged