Helm chart | Added controller.podAnnotations to helm chart
topolvm/pvc-autoresizer pull request #170
Opened 2023-01-20 16:59 UTC by jcortejoso

Added the option to customize controller's podTemplate annotations using a new value `controller.podAnnotations`.

Rationale to introduce this change is being able to configure annotations for Prometheus Kubernetes service discovery, for cases when Prometheus Operator is not being used.

2023-01-23 09:35 UTC, daichimukai requested changes

2023-01-23 09:35 UTC, daichimukai commented on charts/pvc-autoresizer/templates/controller/deployment.yaml
> +      {{ if .Values.controller.podAnnotations -}}
```suggestion
      {{- if .Values.controller.podAnnotations}}
```

Just for consistency.

2023-01-23 09:35 UTC, daichimukai commented on charts/pvc-autoresizer/templates/controller/deployment.yaml
> +      {{ end -}}
```suggestion
      {{- end }}
```

The right trim marker changes the indent of `spec` in the following line. We must keep it.

```diff
@@ -183,7 +183,7 @@
     metadata:
       labels:
         app.kubernetes.io/name: pvc-autoresizer
-    spec:
+      spec:
       serviceAccountName: release-name-pvc-autoresizer-controller
       containers:
         - name: pvc-autoresizer
```

2023-01-24 08:00 UTC, toshipp reviewed
@jcortejoso 
LGTM.
Could you squash commits to pass DCO?

2023-01-24 10:28 UTC, jcortejoso commented
@toshipp done, thanks for reviewing.

2023-01-25 02:41 UTC, toshipp approved these changes

2023-01-27 04:59 UTC, daichimukai approved these changes

2023-01-27 04:59 UTC, merged