artifacthub
topolvm/pvc-autoresizer pull request #181
Opened 2023-02-27 15:50 UTC by bells17

- https://github.com/topolvm/topolvm/issues/368
- #169

2023-02-28 00:49 UTC, toshipp requested changes

2023-02-28 00:49 UTC, toshipp commented on RELEASE.md
> +    $ sed -r -i "s/ghcr.io\/topolvm\/pvc-autoresizer:[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+/ghcr.io\/topolvm\/pvc-autoresizer:${APPVERSION}/g" charts/pvc-autoresizer/Chart.yam
```suggestion
    $ sed -r -i "s/ghcr.io\/topolvm\/pvc-autoresizer:[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+/ghcr.io\/topolvm\/pvc-autoresizer:${APPVERSION}/g" charts/pvc-autoresizer/Chart.yaml
```

2023-02-28 01:54 UTC, bells17 commented on RELEASE.md
> +    $ sed -r -i "s/ghcr.io\/topolvm\/pvc-autoresizer:[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+/ghcr.io\/topolvm\/pvc-autoresizer:${APPVERSION}/g" charts/pvc-autoresizer/Chart.yam
I fixed it.

2023-02-28 05:10 UTC, toshipp approved these changes

2023-03-01 00:22 UTC, pluser approved these changes

2023-03-01 00:22 UTC, merged