kubelet
topolvm/pvc-autoresizer pull request #193
Opened 2023-05-10 18:53 UTC by arturrez

2023-05-12 06:32 UTC, cupnes commented
@arturrez Unfortunately, we cannot accept this PR. It's because this PR uses the kubelet Summary API and this API may be marked as deprecated in the future.[*1]

[*1] https://github.com/kubernetes/kubernetes/issues/68522

2023-05-15 16:38 UTC, arturrez commented
k thank you. let me look into this. I still think that prometheus dependency is not needed as this info is available through k8s api

2023-05-15 21:12 UTC, arturrez commented
@cupnes , I pushed a commit in which I switched to `/metrics` endpoint exposed by `kubelet` instead. Looking forward to your feedback

2023-05-16 11:07 UTC, daichimukai commented
Thank you for your contribution, but I am not very positive about merging this PR. In my opinion, there are difficulties with getting metrics from kubelet instead of prometheus.

For example, I suspect that if there are multiple worker nodes, volumes mounted on pods on different nodes than the pvc-autoresizer controller will not be resized.

Also, I don't know if the pvc-autoresizer controller can connect to kubelet with its service account. Even if it were possible in our e2e test environments, I don't know if this is the case in all environments.

2023-05-16 16:42 UTC, arturrez commented
no worries. Some k8s users don't use prometheus ( like us :) ) but are still interested in automatic pv resizing. Prometheus gather this data from kubelet so it seems to me that prometheus dependency can be removed.
regarding RBAC, `charts/pvc-autoresizer/templates/controller/clusterrole.yaml` in my PR addresses this issue allowing controller to access kubelet API

2023-05-17 01:21 UTC, daichimukai commented
> Prometheus gather this data from kubelet 

I've never heard of this information. Could you provide me with documentation or other sources of information?

2023-05-17 18:44 UTC, arturrez commented
> > Prometheus gather this data from kubelet
> 
> I've never heard of this information. Could you provide me with documentation or other sources of information?

I came across https://observability.thomasriley.co.uk/monitoring-kubernetes/metrics/kubelet-cadvisor/

2023-05-19 09:03 UTC, daichimukai commented
@arturrez 
I After looking at the PR implementation for a bit, I understand that this PR enables us to scrape the metrics using the kubernetes api. It it acceptable for me.

Before we proceed the review of this PR, I have a few requests:

* Check the DCO.
* Rebase and organize your commits. It would be nice to have a commit message explaining what the commit is about.
* I feel `--use-kubelet` is ambiguous. How about `--use-k8s-metrics-api`?
* You are trying to make to use the kubernetes api the default, but please keep the current behavior that uses prometheus as the default.
* Please test both the mode using prometheus and the mode using kubernetes api with CI. Our another project has such settings ([ref](https://github.com/topolvm/topolvm/blob/995c3e2dc8e299fbdb8731f447893906b966a4e4/.github/workflows/e2e-k8s.yaml#L51-L65)). It may help.

2023-05-19 20:08 UTC, arturrez commented
k thank you. will do.

2023-05-30 01:36 UTC, arturrez commented
addressed feedback

2023-05-30 02:03 UTC, daichimukai requested changes
Please avoid merging the main branch to the topic branch; rebase the topic branch to the main branch instead.

2023-05-30 02:03 UTC, daichimukai commented on runners/metrics_client.go
> +func NewKubeletClient() (MetricsClient, error) {
```suggestion
func NewKubernetesMetricsAPIClient() (MetricsClient, error) {
```

2023-05-30 02:03 UTC, daichimukai commented on charts/pvc-autoresizer/values.yaml
> +    # controller.args.useK8sMetricsApii -- Use K8s metrics API to query volume stats.
```suggestion
    # controller.args.useK8sMetricsApi -- Use K8s metrics API to query volume stats.
```

2023-05-30 02:04 UTC, daichimukai commented
> Please test both the mode using prometheus and the mode using kubernetes api with CI. Our another project has such settings (ref). It may help.

This should be addressed too.

2023-07-08 23:34 UTC, closed without merging

2024-02-08 09:05 UTC, tropnikovvl commented
Work continued in this https://github.com/topolvm/pvc-autoresizer/pull/242