feat: support securityContext and podSecurityContext configuration
topolvm/pvc-autoresizer pull request #265
Opened 2024-06-24 13:29 UTC by wparr-circle

… helm chart

2024-06-25 00:41 UTC, ushitora-anqou approved these changes

2024-06-25 00:48 UTC, ushitora-anqou requested changes
Could you please update the README using [this guide](https://github.com/topolvm/pvc-autoresizer/tree/main/charts/pvc-autoresizer#update-readme)? Thanks!

2024-06-26 01:00 UTC, ushitora-anqou approved these changes

2024-07-08 08:09 UTC, pluser approved these changes

2024-07-08 08:09 UTC, merged