Add PriorityClassName and Affinity
topolvm/pvc-autoresizer pull request #285
Opened 2024-10-24 18:54 UTC by josephangbc

closes #284

2024-10-28 09:22 UTC, toshipp requested changes
almost good. I left some comments, please check it.

2024-10-28 09:22 UTC, toshipp commented on charts/pvc-autoresizer/values.yaml
> +  # controller.priorityClassName -- riority class name to be applied to the controller pods.
```suggestion
  # controller.priorityClassName -- priority class name to be applied to the controller pods.
```

2024-10-28 09:22 UTC, toshipp commented on charts/pvc-autoresizer/values.yaml
> +    #   podAntiAffinity:
It seems to be the wrong indentation.

2024-10-28 09:22 UTC, toshipp commented on charts/pvc-autoresizer/templates/controller/deployment.yaml
> +    {{- if .Values.controller.priorityClassName }}
Could you use `with` instead?

2024-10-28 10:30 UTC, josephangbc commented on charts/pvc-autoresizer/values.yaml
> +  # controller.priorityClassName -- riority class name to be applied to the controller pods.
Updated the example comments

2024-10-28 10:30 UTC, josephangbc commented on charts/pvc-autoresizer/values.yaml
> +    #   podAntiAffinity:
Updated the indentation

2024-10-29 00:05 UTC, satoru-takeuchi approved these changes

2024-10-29 04:51 UTC, toshipp commented
@josephangbc 
Could you re-generate `charts/pvc-autoresizer/README.md`?
The instruction is `make generate-helm-docs`. If you didn't setup tools, please `make setup` first.

2024-10-30 04:31 UTC, toshipp approved these changes

2024-10-30 07:52 UTC, satoru-takeuchi approved these changes

2024-10-30 07:52 UTC, merged