Stop the display of usage when the program terminates with an error.
topolvm/pvc-autoresizer pull request #34
Opened 2021-04-27 08:54 UTC by llamerada-jp

Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>

2021-04-27 08:56 UTC, ymmt2005 requested changes

2021-04-27 08:56 UTC, ymmt2005 commented on cmd/root.go
> +	SilenceUsage: true,
This should be set in `RunE`, or you never get usage message even when the usage is wrong.
Please see our other products.

2021-04-28 03:24 UTC, ymmt2005 approved these changes
LGTM

2021-04-28 04:19 UTC, satoru-takeuchi approved these changes

2021-04-28 05:46 UTC, merged